
package controlcontacto.appescritorio;

// Importaciones para el funcionamiento de la pantalla de Login
import controlcontacto.appescritorio.utils.*; // importar todas las clases de utilidades de la aplicaciones escritorio
import controlcontacto.accesoadatos.*; // importar todas la clases de la capa de acceso a datos
import controlcontactos.entidadesdenegocio.*; // importar todas la clases de la capa de entidades de negocio
import javax.swing.JOptionPane; // importa la clase JOptionPane para mostrar alertas o advertencias a los usuarios

public class FrmLogin extends javax.swing.JFrame {

    /**
     * Creates new form FrmLogin
     */
    public FrmLogin() {
        initComponents();
    }

    // <editor-fold defaultstate="collapsed" desc="Metodos locales de la clase FrmLogin">
    private void iniciarSesion() {
        try {
            Usuario usuario = new Usuario();
            // Obtener el valor de la caja de texto Login de la pantalla y llenar la propiedad Login de la clase Usuario
            usuario.setLogin(this.txtLogin.getText());
            String pass = new String(this.txtPassword.getPassword()); // Obtener el valor de la caja de texto Password de la pantalla de Login
            usuario.setPassword(pass); // Llenar la propiedad Password de la clase Usuario
            // Validar que la propiedad Login y Password no este vacios
            if (usuario.getLogin().trim().isEmpty() == false && usuario.getPassword().trim().isEmpty() == false) {
                Usuario usuarioAut = UsuarioDAL.login(usuario); // Autentificar el usuario en la base de datos
                // Si el Id es mayor a cero y Login que retorno el metodo de login() es igual al login que enviamos es un
                // usuario autorizado en el sistema
                if (usuarioAut.getId() > 0 && usuarioAut.getLogin().equals(usuario.getLogin())) {
                    // Llenar la propiedad Id de la clase UsuarioAutorizado para mantenerla en cache en todo el sistema
                    UsuarioAutorizado.setId(usuarioAut.getId());
                    // Llenar la propiedad Login de la clase UsuarioAutorizado para mantenerla en cache en todo el sistema
                    UsuarioAutorizado.setLogin(usuarioAut.getLogin());
                    FrmInicio frmInicio = new FrmInicio(); // Instanciar el formulario de Inicio
                    frmInicio.setVisible(true); // Mostrar el formulario de Inicio
                    this.setVisible(false); // Cerrar el formulario del Login
                } else {
                    // Mostrar un mensaje al usuario que usa la pantalla  que login y password son incorrectos
                    JOptionPane.showMessageDialog(this, "El login y password son incorrectos");
                    // Limpiar la caja de texto del password en la pantalla de login
                    this.txtPassword.setText("");
                }
            } else {
                // Mostrar un mensaje al usuario que usa la pantalla  que login y password son obligatorios
                JOptionPane.showMessageDialog(this, "El login y password son obligatorios");
            }
        } catch (Exception ex) {
            // Mostrar un mensaje al usuario que usa la pantalla  sucedio un error al momento de autentificar el usuario
            JOptionPane.showMessageDialog(this, "Sucedio el siguiente error: " + ex.getMessage());
        }
    }

    // </editor-fold> 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBg = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        txtLogin = new javax.swing.JTextField();
        btnIniciar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Iniciar sesión SysSeguridad");
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(600, 400));

        pnlBg.setBackground(new java.awt.Color(255, 255, 255));
        pnlBg.setForeground(new java.awt.Color(255, 255, 255));
        pnlBg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jLabel1.setText("Login");
        pnlBg.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 40, -1));

        jLabel2.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jLabel2.setText("Password");
        pnlBg.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        txtPassword.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        txtPassword.setBorder(null);
        pnlBg.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 230, 30));

        txtLogin.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        txtLogin.setBorder(null);
        pnlBg.add(txtLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 230, 30));

        btnIniciar.setBackground(new java.awt.Color(76, 219, 196));
        btnIniciar.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        btnIniciar.setForeground(new java.awt.Color(255, 255, 255));
        btnIniciar.setMnemonic('I');
        btnIniciar.setText("Iniciar");
        btnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarActionPerformed(evt);
            }
        });
        pnlBg.add(btnIniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 210, 110, 40));

        btnSalir.setBackground(new java.awt.Color(165, 237, 226));
        btnSalir.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(153, 153, 153));
        btnSalir.setMnemonic('S');
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        pnlBg.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, 110, 40));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/controlcontacto/appescritorio/images/usuario.png"))); // NOI18N
        pnlBg.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, -4, 220, 390));
        pnlBg.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 230, 10));
        pnlBg.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 230, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 571, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // ************ Eventos de la pantalla de Login **********************
    
    // Evento que se produce al hacer click o pulsar espaciadora o enter sobre el boton
    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed
        this.iniciarSesion(); // Llamar al metodo local iniciarSesion()
    }//GEN-LAST:event_btnIniciarActionPerformed
    // Evento que se produce al hacer click o pulsar espaciadora o enter sobre el boton
    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed

        this.dispose(); // cerrar el formulario
        System.exit(0); // cerrar el sistema, usar para cerrar el sistema completamente
    }//GEN-LAST:event_btnSalirActionPerformed

     // ************ Fin de los eventos de la pantalla de Login **********************
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel pnlBg;
    private javax.swing.JTextField txtLogin;
    private javax.swing.JPasswordField txtPassword;
    // End of variables declaration//GEN-END:variables
}
